title: "Cool Stuff"
subtitle: "The coolest stuff on the internet"
description: "A daily-updating list of the coolest websites on the web."
url: "https://cool-stuff.co.uk"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.26.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-data

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: archive
    values:
      layout: archive

include:
  - docs/_pages
  - docs/_data
  - docs/feed.xml

# Optional: if deploying on GitHub Pages
github:
  is_project_page: false

